baseURL = 'https://anidotdev.github.io/'
languageCode = 'en-us'
title = 'Hi, I am Animesh'

theme = 'hugo-bearblog'

# Fix ugly URLs + clean permalinks
uglyURLs = false

[permalinks]
  posts = '/posts/:slug/'
  projects = '/projects/:slug/'

[build]
  writeStats = true

[params]
  Description = "Minimalist blog."
  Dateform = "Jan 2, 2006"
  Author = "Animesh Gautam"

[markup.goldmark.renderer]
  unsafe = true  # For inline SVG

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
  name = "Blog"
  url = "/posts/"

[[menu.main]]
  name = "Projects"
  url = "/projects/"
