baseURL = 'https://animeshhq.github.io/'
languageCode = 'en-us'
title = 'Hi, I am Animesh'

theme = 'hugo-bearblog'

[build]
  writeStats = true

[params]
  Description = "Minimalist blog."
  Dateform = "Jan 2, 2006"
  Author = "Animesh Gautam"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
  name = "Blog"  # Auto-links to /posts/
  url = "posts/"  # No leading / safe

[[menu.main]]
  name = "Projects"
  url = "projects/"
